"use client"

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import { Provider } from 'react-redux'
// import {createStore} from "redux";
// import rootReducer from "@/redux/reducers";
const inter = Inter({ subsets: ['latin'] })
import store from "@/redux/store";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
// const store = createStore(rootReducer);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={"max-w-[500px] w-full h-full"}>
            <Provider store={store}>
                {children}
            </Provider>
        </div>
      </body>
    </html>
  )
}
